NIFTY50_TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
    "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "BAJFINANCE.NS", "LT.NS",
    "KOTAKBANK.NS", "HCLTECH.NS", "ASIANPAINT.NS", "AXISBANK.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS", "TATAMOTORS.NS", "BAJAJFINSV.NS",
    "WIPRO.NS", "NESTLEIND.NS", "M&M.NS", "POWERGRID.NS", "JSWSTEEL.NS",
    "TATASTEEL.NS", "NTPC.NS", "ADANIENT.NS", "ONGC.NS", "GRASIM.NS",
    "HINDUNILVR.NS", "TECHM.NS", "HINDALCO.NS", "DIVISLAB.NS", "ADANIPORTS.NS",
    "CIPLA.NS", "DRREDDY.NS", "BRITANNIA.NS", "APOLLOHOSP.NS", "EICHERMOT.NS",
    "COALINDIA.NS", "TATACONSUM.NS", "HEROMOTOCO.NS", "BAJAJ-AUTO.NS",
    "UPL.NS", "BPCL.NS", "INDUSINDBK.NS", "SHREECEM.NS", "HDFCLIFE.NS",
    "SBILIFE.NS"
]
